# parameters.yaml: Configuration parameters for SkyOptima

# Model parameters
arima_order: [1, 1, 1]
lstm_epochs: 10
lstm_batch_size: 4
xgboost_n_estimators: 100

# Data processing parameters
feature_lag: 3
rolling_window: 3

# Pricing parameters
base_price: 250.0
price_elasticity: 0.1

# System performance thresholds
max_data_latency_seconds: 5
target_uptime: 99.99

# Security parameters
encryption_key_path: "config/encryption.key"
